/*
 * main.c — RecCompiler CLI with built-in mini editor.
 *
 * Usage:
 *   reccompiler run  <file.c>           Compile and run
 *   reccompiler edit <file.c>           Open built-in editor
 *   reccompiler asm  <file.c>           Show generated bytecode
 *   reccompiler help                    Show usage
 */

#include "lexer.h"
#include "parser.h"
#include "compiler.h"
#include "vm.h"

/* ── File I/O ───────────────────────────────────────────── */
static char *read_file(const char *path) {
    FILE *f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "Error: cannot open '%s'\n", path); return NULL; }
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    char *buf = (char *)malloc(len + 1);
    if (!buf) { fclose(f); return NULL; }
    fread(buf, 1, len, f);
    buf[len] = '\0';
    fclose(f);
    return buf;
}

static int write_file(const char *path, const char *content) {
    FILE *f = fopen(path, "w");
    if (!f) { fprintf(stderr, "Error: cannot write '%s'\n", path); return -1; }
    fputs(content, f);
    fclose(f);
    return 0;
}

/* ── Compile & Run pipeline ─────────────────────────────── */
static int compile_and_run(const char *source, bool show_asm) {
    Lexer lexer;
    lexer_init(&lexer, source);

    ASTNode *ast = parser_parse(&lexer);

    Program prog;
    compiler_compile(ast, &prog);

    if (show_asm) {
        compiler_disassemble(&prog);
        printf("\n--- Output ---\n");
    }

    int result = vm_execute(&prog);

    ast_free(ast);
    return result;
}

/* ── Mini Editor ────────────────────────────────────────── */
#define MAX_EDITOR_LINES 1024
#define MAX_LINE_LEN     256

static char editor_lines[MAX_EDITOR_LINES][MAX_LINE_LEN];
static int  editor_line_count = 0;

static void editor_load(const char *path) {
    editor_line_count = 0;
    FILE *f = fopen(path, "r");
    if (!f) return;
    while (editor_line_count < MAX_EDITOR_LINES &&
           fgets(editor_lines[editor_line_count], MAX_LINE_LEN, f)) {
        /* Strip trailing newline */
        char *nl = strchr(editor_lines[editor_line_count], '\n');
        if (nl) *nl = '\0';
        editor_line_count++;
    }
    fclose(f);
}

static char *editor_to_string(void) {
    /* Calculate total length */
    int total = 0;
    for (int i = 0; i < editor_line_count; i++)
        total += (int)strlen(editor_lines[i]) + 1;  /* +1 for newline */

    char *buf = (char *)malloc(total + 1);
    if (!buf) return NULL;
    buf[0] = '\0';
    for (int i = 0; i < editor_line_count; i++) {
        strcat(buf, editor_lines[i]);
        strcat(buf, "\n");
    }
    return buf;
}

static void editor_list(void) {
    if (editor_line_count == 0) {
        printf("  (empty)\n");
        return;
    }
    for (int i = 0; i < editor_line_count; i++)
        printf("  %3d | %s\n", i + 1, editor_lines[i]);
}

static void editor_help(void) {
    printf("\n");
    printf("  Commands:\n");
    printf("    :save          Save file\n");
    printf("    :run           Save, compile and run\n");
    printf("    :list          Show code with line numbers\n");
    printf("    :del <N>       Delete line N\n");
    printf("    :clear         Clear all code\n");
    printf("    :quit / :q     Exit editor\n");
    printf("    :help          Show this help\n");
    printf("\n");
    printf("  Type code directly to add lines.\n\n");
}

static void run_editor(const char *path) {
    printf("\n");
    printf("  ╔══════════════════════════════════════╗\n");
    printf("  ║       RecCompiler Mini Editor        ║\n");
    printf("  ╠══════════════════════════════════════╣\n");
    printf("  ║  Type code lines, or use :commands   ║\n");
    printf("  ║  :help for all commands              ║\n");
    printf("  ╚══════════════════════════════════════╝\n");
    printf("  File: %s\n\n", path);

    /* Load existing file if present */
    editor_load(path);
    if (editor_line_count > 0) {
        printf("  Loaded %d lines from %s\n", editor_line_count, path);
        editor_list();
    }

    char input[MAX_LINE_LEN];
    for (;;) {
        printf("%3d> ", editor_line_count + 1);
        fflush(stdout);

        if (!fgets(input, sizeof(input), stdin)) break;

        /* Strip trailing newline */
        char *nl = strchr(input, '\n');
        if (nl) *nl = '\0';

        /* Check for commands */
        if (input[0] == ':') {
            if (strcmp(input, ":quit") == 0 || strcmp(input, ":q") == 0) {
                printf("  Goodbye!\n");
                break;
            }
            if (strcmp(input, ":save") == 0) {
                char *content = editor_to_string();
                if (content) {
                    write_file(path, content);
                    free(content);
                    printf("  Saved to %s (%d lines)\n", path, editor_line_count);
                }
                continue;
            }
            if (strcmp(input, ":run") == 0) {
                char *content = editor_to_string();
                if (content) {
                    write_file(path, content);
                    printf("  Saved to %s\n", path);
                    printf("  Compiling & running...\n\n");
                    compile_and_run(content, false);
                    printf("\n");
                    free(content);
                }
                continue;
            }
            if (strcmp(input, ":list") == 0) {
                editor_list();
                continue;
            }
            if (strcmp(input, ":clear") == 0) {
                editor_line_count = 0;
                printf("  Cleared.\n");
                continue;
            }
            if (strcmp(input, ":help") == 0) {
                editor_help();
                continue;
            }
            if (strncmp(input, ":del ", 5) == 0) {
                int n = atoi(input + 5);
                if (n < 1 || n > editor_line_count) {
                    printf("  Invalid line number.\n");
                } else {
                    for (int i = n - 1; i < editor_line_count - 1; i++)
                        strcpy(editor_lines[i], editor_lines[i + 1]);
                    editor_line_count--;
                    printf("  Deleted line %d.\n", n);
                }
                continue;
            }
            printf("  Unknown command. Type :help\n");
            continue;
        }

        /* Regular line — add to editor */
        if (editor_line_count >= MAX_EDITOR_LINES) {
            printf("  Maximum lines reached!\n");
            continue;
        }
        strncpy(editor_lines[editor_line_count], input, MAX_LINE_LEN - 1);
        editor_lines[editor_line_count][MAX_LINE_LEN - 1] = '\0';
        editor_line_count++;
    }
}

/* ── Usage ──────────────────────────────────────────────── */
static void print_usage(void) {
    printf("\n");
    printf("  RecCompiler — Mini C Compiler with Recursion Support\n");
    printf("  ====================================================\n\n");
    printf("  Usage:\n");
    printf("    reccompiler run  <file.c>    Compile and run a program\n");
    printf("    reccompiler edit <file.c>    Open the built-in mini editor\n");
    printf("    reccompiler asm  <file.c>    Show bytecode + run\n");
    printf("    reccompiler help             Show this help\n\n");
    printf("  Supported C features:\n");
    printf("    - Types: int, void\n");
    printf("    - Functions with recursion (including mutual recursion)\n");
    printf("    - if/else, while, for\n");
    printf("    - Operators: + - * / %% == != < > <= >= && || !\n");
    printf("    - Built-ins: print(expr), scan()\n\n");
    printf("  Example:\n");
    printf("    reccompiler edit factorial.c\n");
    printf("    reccompiler run  factorial.c\n\n");
}

/* ── Main ───────────────────────────────────────────────── */
int main(int argc, char **argv) {
    if (argc < 2) {
        print_usage();
        return 0;
    }

    const char *cmd = argv[1];

    if (strcmp(cmd, "help") == 0 || strcmp(cmd, "--help") == 0 ||
        strcmp(cmd, "-h") == 0) {
        print_usage();
        return 0;
    }

    if (strcmp(cmd, "edit") == 0) {
        if (argc < 3) {
            fprintf(stderr, "Usage: reccompiler edit <file.c>\n");
            return 1;
        }
        run_editor(argv[2]);
        return 0;
    }

    if (strcmp(cmd, "run") == 0) {
        if (argc < 3) {
            fprintf(stderr, "Usage: reccompiler run <file.c>\n");
            return 1;
        }
        char *source = read_file(argv[2]);
        if (!source) return 1;
        int result = compile_and_run(source, false);
        free(source);
        return result;
    }

    if (strcmp(cmd, "asm") == 0) {
        if (argc < 3) {
            fprintf(stderr, "Usage: reccompiler asm <file.c>\n");
            return 1;
        }
        char *source = read_file(argv[2]);
        if (!source) return 1;
        int result = compile_and_run(source, true);
        free(source);
        return result;
    }

    /* Default: treat first arg as a filename → run */
    char *source = read_file(cmd);
    if (!source) {
        fprintf(stderr, "Unknown command '%s'. Try: reccompiler help\n", cmd);
        return 1;
    }
    int result = compile_and_run(source, false);
    free(source);
    return result;
}
